[vm_pre]
158.158.2.107 ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/id_rsa_tfg ansible_python_interpreter=/usr/bin/python3

[vm_pro]
# SUSTITUIR por la IP de la VM de PRO cuando se cree
# X.X.X.X ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/id_rsa_tfg ansible_python_interpreter=/usr/bin/python3
