name: Ansible — Configurar VM

on:
  push:
    branches:
      - develop
      - main

jobs:
  ansible:
    name: Configurar VM ${{ github.ref_name == 'main' && 'PRO' || 'PRE' }}
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'pro' || 'pre' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determinar entorno
        id: entorno
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "nombre=PRO" >> $GITHUB_OUTPUT
            echo "workspace=Infraestructura_Pro" >> $GITHUB_OUTPUT
          else
            echo "nombre=PRE" >> $GITHUB_OUTPUT
            echo "workspace=Infraestructura_Pre" >> $GITHUB_OUTPUT
          fi

      - name: Obtener IP desde Terraform Cloud
        id: tf_output
        run: |
          WORKSPACE_ID=$(curl -s \
            --header "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            "https://app.terraform.io/api/v2/organizations/${{ vars.TF_ORGANIZATION }}/workspaces/${{ steps.entorno.outputs.workspace }}" \
            | jq -r '.data.id')

          VM_IP=$(curl -s \
            --header "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            "https://app.terraform.io/api/v2/workspaces/${WORKSPACE_ID}/current-state-version-outputs" \
            | jq -r '.data[] | select(.attributes.name == "vm_public_ip") | .attributes.value')

          echo "vm_ip=${VM_IP}" >> $GITHUB_OUTPUT
          echo "IP de VM ${{ steps.entorno.outputs.nombre }}: ${VM_IP}"

      - name: Instalar Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Configurar clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_tfg
          chmod 600 ~/.ssh/id_rsa_tfg
          ssh-keyscan -H ${{ steps.tf_output.outputs.vm_ip }} >> ~/.ssh/known_hosts

      - name: Crear inventario dinámico
        run: |
          cat > ansible/inventory_ci.ini << EOF2
          [vm_target]
          ${{ steps.tf_output.outputs.vm_ip }} ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/id_rsa_tfg ansible_python_interpreter=/usr/bin/python3
          EOF2

      - name: Ejecutar playbook Ansible
        run: |
          ansible-playbook -i ansible/inventory_ci.ini ansible/playbook.yml \
            -e "app_user=azureuser \
                app_dir=/opt/microservicio \
                app_port=8000 \
                entorno_tipo=${{ steps.entorno.outputs.nombre }}"
